repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
